server:
   port: 8099
   
eureka:
  client:
    registerWithEureka: false    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
    a:      
      path: /micro-a/**
      sensitiveHeaders:
      url: http://localhost:8080
    b:
      path: /micro-b/**
      sensitiveHeaders:
      url: http://localhost:8081
    
      